### PR TITLE
Replace old IOTA Icon with New Icon

### PR DESCRIPTION
**Pull request by kwko**
First GitHub Pull Request - Apologies if I didn't follow the correct procedure.

### CODE REVIEW

**Comment by peterwilli** [comment]
@kwko oh my god, thanks! Can you give your wallet address? I want to forward some of the donations I got to thank you for this!

**Comment by kwko** [comment]
Thank you! Wow, very generous of you! 
My Address is : L9VMPSIWKMXECFUNZYVUPTYA9LYSZPHGJPFOQVBGFYAFJBWCIYKIFWONDJNIPBHJ9AKOUVGTJNZBWJ9ICZISLODJGA
Can't wait to see how you get on with it! Let me know and I'll post an update on www.ukcryptocurrency.com

**Comment by peterwilli** [comment]
Hi @kwko sorry to bother you, but is your address `L9VMPSIWKMXECFUNZYVUPTYA9LYSZPHGJPFOQVBGFYAFJBWCIYKIFWONDJNIPBHJ9AKOUVGTJNZBWJ9ICZISLODJGA` still valid? The Ledger-team just cashed out and we've got 100Mi and a big thanks on behalf of my team and the community lying around for you :+1:

**Comment by kwko** [comment]
Ah cool! Thank you very much! My address
is SFKYHYARIZZUSTBHKJ9YCFVCWUTJCAKUVTUXGHAMPTJDMTJWDFXAKZGETVUKKTLT9VZGICHZRZOGHM9EDKCVDRTZUC
Kind regards,
Ben

**Comment by peterwilli** [comment]
@kwko ok I'll send it now!
Edit: https://iotasear.ch/transaction/UYRUMBENXEGFBE9ONZAHWZZYTYIXWNPOFPONQMBPDHJOHKEFV99X9IUFBOIRFVOAACTAGHTKUDAT99999

Thanks again! (also the money has been transferred from a Ledger wallet :))

**Pull request merged**
